#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OFFLINE_DIR="$ROOT/offline"
mkdir -p "$OFFLINE_DIR/npm-cache" "$OFFLINE_DIR/cargo"

echo "[1/3] 准备 npm 离线缓存 -> offline/npm-cache"
(
  cd "$ROOT/web"
  npm ci --cache "$OFFLINE_DIR/npm-cache" --prefer-offline --no-audit --fund=false
)

echo "[2/3] 准备 Cargo vendor -> offline/cargo/vendor"
(
  cd "$ROOT"
  CARGO_NET_OFFLINE=false cargo vendor "$OFFLINE_DIR/cargo/vendor" > "$OFFLINE_DIR/cargo/config.toml"
)

echo "[3/3] 生成离线说明索引"
cat > "$OFFLINE_DIR/README.md" <<'EOF'
# DM offline dependency cache

This directory is generated by `scripts/prepare-offline-deps.sh`.

- `npm-cache/`: npm cache for `web/package-lock.json`.
- `cargo/vendor/`: Cargo vendored crates.
- `cargo/config.toml`: Cargo source replacement snippet.

Use `docs/OFFLINE-DEVELOPMENT.md` for the full offline workflow.
EOF

echo "[OK] 离线依赖已准备完成"
